version: "3.8"
services:
  mongo:
    image: mongo
    restart: always
    container_name: ior_mongo
    ports:
      - 27017:27017

  frontend_and_backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: frontend_and_backend
    command: sh -c "yarn install && yarn dev"
    ports:
      - 3000:3000
    volumes:
      - .:/ior
      - /ior/node_modules
