name: IorTest # work flow name
on: [push] # tining of ignition work flow
jobs:
  eslint:
    name: eslint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: yarn install
        run: yarn install
      # - name: eslint review
      #   uses: reviewdog/action-eslint@v1
      #   with:
      #     github_token: ${{ secrets.github_token }}
      #     reporter: github-pr-review
      #     eslint_flags: './**/*.{ts,js}'
      - name: eslint
        run: yarn lint